import { useState, useEffect } from "react";
import { Input } from "@/components/common/Input";
import { Button } from "@/components/common/Button";
import { Card } from "@/components/common/Card";
import SlugInput from "@/components/admin/experiences/SlugInput";
import ImageUpload from "@/components/admin/experiences/ImageUpload";
import { slugify, checkSlugAvailable } from "@/hooks/usePublications";
import { useExperiences } from "@/hooks/useExperiences";
import AdminSelect from "@/components/common/AdminSelect";
import SearchCombobox from "@/components/common/SearchCombobox";
import { cn } from "@/lib/utils";

const CATEGORY_OPTIONS = [
  { value: "landing", label: "Landing" },
  { value: "blog", label: "Blog" },
  { value: "highlight", label: "Highlight" },
  { value: "institutional", label: "Institucional" },
  { value: "faq", label: "FAQ" },
];

const STATUS_OPTIONS = [
  { value: "draft", label: "Borrador" },
  { value: "published", label: "Publicada" },
  { value: "archived", label: "Archivada" },
];

const EMPTY = {
  title: "",
  titleEs: "",
  slug: "",
  subtitle: "",
  subtitleEs: "",
  excerpt: "",
  excerptEs: "",
  category: "blog",
  experienceId: "",
  heroImageId: "",
  status: "draft",
  publishedAt: "",
  seoTitle: "",
  seoDescription: "",
  ogImageId: "",
};

/* ---------- sub-components ---------- */

function Field({ label, required, error, hint, children }) {
  return (
    <div className="space-y-1.5">
      <label className="text-sm font-medium text-charcoal">
        {label}
        {required && <span className="text-red-500 ml-0.5">*</span>}
      </label>
      {children}
      {error && <p className="text-xs text-red-600">{error}</p>}
      {hint && !error && <p className="text-xs text-charcoal-subtle">{hint}</p>}
    </div>
  );
}

function Textarea({
  value,
  onChange,
  placeholder,
  disabled,
  rows = 3,
  maxLength,
  error,
}) {
  return (
    <textarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      disabled={disabled}
      rows={rows}
      maxLength={maxLength}
      className={cn(
        "flex w-full rounded-xl border border-sand-dark bg-white px-4 py-3 text-sm text-charcoal placeholder:text-charcoal-subtle",
        "focus:outline-none focus:border-sage focus:ring-2 focus:ring-sage/20 resize-none",
        "disabled:opacity-50 disabled:bg-warm-gray",
        error && "border-red-400",
      )}
    />
  );
}

/* ---------- main form ---------- */

export default function PublicationForm({
  initialData,
  onSubmit,
  submitting,
  submitLabel = "Guardar",
}) {
  const [form, setForm] = useState({ ...EMPTY, ...initialData });
  const [errors, setErrors] = useState({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(
    !initialData?.slug,
  );

  // Load experiences for the optional link
  const { data: experiences } = useExperiences({
    status: "published",
    limit: 100,
    offset: 0,
  });

  function set(field, value) {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (errors[field])
      setErrors((prev) => {
        const e = { ...prev };
        delete e[field];
        return e;
      });
  }

  function handleTitle(value) {
    set("title", value);
    if (slugAutoGenerated) {
      set("slug", slugify(value));
    }
  }

  function handleSlugChange(value) {
    setSlugAutoGenerated(false);
    set("slug", value);
  }

  async function validate() {
    const e = {};
    if (!form.title.trim()) e.title = "El título es requerido";
    if (!form.slug.trim()) {
      e.slug = "El slug es requerido";
    } else if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(form.slug)) {
      e.slug = "Solo minúsculas, números y guiones";
    } else {
      const available = await checkSlugAvailable(form.slug, initialData?.$id);
      if (!available) e.slug = "Este slug ya está en uso";
    }
    if (!form.category) e.category = "La categoría es requerida";
    return e;
  }

  async function handleSubmit(e) {
    e.preventDefault();
    const validationErrors = await validate();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    const payload = {
      title: form.title.trim(),
      titleEs: form.titleEs.trim() || null,
      slug: form.slug.trim(),
      subtitle: form.subtitle.trim() || null,
      subtitleEs: form.subtitleEs.trim() || null,
      excerpt: form.excerpt.trim() || null,
      excerptEs: form.excerptEs.trim() || null,
      category: form.category,
      experienceId: form.experienceId || null,
      heroImageId: form.heroImageId || null,
      status: form.status,
      publishedAt:
        form.status === "published" && !form.publishedAt
          ? new Date().toISOString()
          : form.publishedAt || null,
      seoTitle: form.seoTitle.trim() || null,
      seoDescription: form.seoDescription.trim() || null,
      ogImageId: form.ogImageId || null,
    };

    await onSubmit(payload);
  }

  const isDisabled = submitting;

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Identidad */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Identidad
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field label="Título (EN)" required error={errors.title}>
            <Input
              value={form.title}
              onChange={(e) => handleTitle(e.target.value)}
              placeholder="The Art of Stillness"
              disabled={isDisabled}
              className={errors.title ? "border-red-400" : ""}
            />
          </Field>
          <Field label="Título (ES)">
            <Input
              value={form.titleEs}
              onChange={(e) => set("titleEs", e.target.value)}
              placeholder="El Arte de la Quietud"
              disabled={isDisabled}
            />
          </Field>
          <Field label="Slug (URL)" required error={errors.slug}>
            <SlugInput
              value={form.slug}
              onChange={handleSlugChange}
              error={errors.slug}
              disabled={isDisabled}
            />
          </Field>
          <Field label="Categoría" required error={errors.category}>
            <AdminSelect
              value={form.category}
              onChange={(v) => set("category", v)}
              options={CATEGORY_OPTIONS}
              disabled={isDisabled}
              error={!!errors.category}
            />
          </Field>
        </div>
      </Card>

      {/* Subtítulos y extracto */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Subtítulo y extracto
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field label="Subtítulo (EN)" hint="Máx. 500 caracteres">
            <Input
              value={form.subtitle}
              onChange={(e) => set("subtitle", e.target.value)}
              placeholder="Discover the power of mindful immersion"
              disabled={isDisabled}
              maxLength={500}
            />
          </Field>
          <Field label="Subtítulo (ES)">
            <Input
              value={form.subtitleEs}
              onChange={(e) => set("subtitleEs", e.target.value)}
              placeholder="Descubre el poder de la inmersión consciente"
              disabled={isDisabled}
              maxLength={500}
            />
          </Field>
          <Field label="Extracto (EN)" hint="Resumen corto para listados">
            <Textarea
              value={form.excerpt}
              onChange={(v) => set("excerpt", v)}
              placeholder="A brief introduction..."
              disabled={isDisabled}
              rows={3}
            />
          </Field>
          <Field label="Extracto (ES)">
            <Textarea
              value={form.excerptEs}
              onChange={(v) => set("excerptEs", v)}
              placeholder="Una breve introducción..."
              disabled={isDisabled}
              rows={3}
            />
          </Field>
        </div>
      </Card>

      {/* Experiencia vinculada */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Experiencia vinculada
        </h2>
        <Field
          label="Experiencia"
          hint="Opcional — vincula esta publicación a una experiencia"
        >
          <SearchCombobox
            value={form.experienceId}
            onValueChange={(v) => set("experienceId", v)}
            options={(experiences || []).map((exp) => ({
              value: exp.$id,
              label: exp.publicName || exp.name,
            }))}
            disabled={isDisabled}
            placeholder="Sin experiencia vinculada"
            searchPlaceholder="Buscar experiencia"
            emptyMessage="No se encontraron experiencias."
          />
        </Field>
      </Card>

      {/* Imagen de portada */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Imagen de portada
        </h2>
        <div className="max-w-lg">
          <ImageUpload
            fileId={form.heroImageId}
            onUpload={(id) => set("heroImageId", id)}
            onRemove={() => set("heroImageId", "")}
            disabled={isDisabled}
          />
        </div>
      </Card>

      {/* Publicación */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Publicación
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Field label="Estado" required>
            <AdminSelect
              value={form.status}
              onChange={(v) => set("status", v)}
              options={STATUS_OPTIONS}
              disabled={isDisabled}
            />
          </Field>
          {form.status === "published" && (
            <Field
              label="Fecha de publicación"
              hint="Se asigna automáticamente si se deja vacío"
            >
              <Input
                type="datetime-local"
                value={form.publishedAt ? form.publishedAt.slice(0, 16) : ""}
                onChange={(e) =>
                  set(
                    "publishedAt",
                    e.target.value
                      ? new Date(e.target.value).toISOString()
                      : "",
                  )
                }
                disabled={isDisabled}
              />
            </Field>
          )}
        </div>
      </Card>

      {/* SEO */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          SEO
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field label="SEO Title" hint="Máx. 255 caracteres">
            <Input
              value={form.seoTitle}
              onChange={(e) => set("seoTitle", e.target.value)}
              placeholder="The Art of Stillness | OMZONE"
              disabled={isDisabled}
              maxLength={255}
            />
          </Field>
          <Field label="SEO Description" hint="Máx. 500 caracteres">
            <Textarea
              value={form.seoDescription}
              onChange={(v) => set("seoDescription", v)}
              placeholder="Discover our transformative wellness..."
              disabled={isDisabled}
              maxLength={500}
              rows={2}
            />
          </Field>
        </div>
        <div className="max-w-lg">
          <Field
            label="OG Image"
            hint="Imagen para compartir en redes sociales"
          >
            <ImageUpload
              fileId={form.ogImageId}
              onUpload={(id) => set("ogImageId", id)}
              onRemove={() => set("ogImageId", "")}
              disabled={isDisabled}
            />
          </Field>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex items-center gap-3 pb-6">
        <Button type="submit" disabled={isDisabled} size="md">
          {submitting ? (
            <span className="flex items-center gap-2">
              <span className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin" />
              Guardando...
            </span>
          ) : (
            submitLabel
          )}
        </Button>
      </div>
    </form>
  );
}
