import { useState, useEffect } from "react";
import { Input } from "@/components/common/Input";
import { Button } from "@/components/common/Button";
import { Card } from "@/components/common/Card";
import SlugInput from "@/components/admin/experiences/SlugInput";
import ImageUpload from "@/components/admin/experiences/ImageUpload";
import { slugify, checkSlugAvailable } from "@/hooks/usePublications";
import { useExperiences } from "@/hooks/useExperiences";
import AdminSelect from "@/components/common/AdminSelect";
import SearchCombobox from "@/components/common/SearchCombobox";
import { cn } from "@/lib/utils";
import { useLanguage } from "@/hooks/useLanguage";

const CATEGORY_OPTIONS = [
  { value: "landing", i18nKey: "admin.publicationCategories.landing" },
  { value: "blog", i18nKey: "admin.publicationCategories.blog" },
  { value: "highlight", i18nKey: "admin.publicationCategories.highlight" },
  {
    value: "institutional",
    i18nKey: "admin.publicationCategories.institutional",
  },
  { value: "faq", i18nKey: "admin.publicationCategories.faq" },
];

const STATUS_OPTIONS = [
  { value: "draft", i18nKey: "admin.statuses.draft" },
  { value: "published", i18nKey: "admin.statuses.published" },
  { value: "archived", i18nKey: "admin.statuses.archived" },
];

const EMPTY = {
  title: "",
  titleEs: "",
  slug: "",
  subtitle: "",
  subtitleEs: "",
  excerpt: "",
  excerptEs: "",
  category: "blog",
  experienceId: "",
  heroImageId: "",
  status: "draft",
  publishedAt: "",
  seoTitle: "",
  seoDescription: "",
  ogImageId: "",
};

/* ---------- sub-components ---------- */

function Field({ label, required, error, hint, children }) {
  return (
    <div className="space-y-1.5">
      <label className="text-sm font-medium text-charcoal">
        {label}
        {required && <span className="text-red-500 ml-0.5">*</span>}
      </label>
      {children}
      {error && <p className="text-xs text-red-600">{error}</p>}
      {hint && !error && <p className="text-xs text-charcoal-subtle">{hint}</p>}
    </div>
  );
}

function Textarea({
  value,
  onChange,
  placeholder,
  disabled,
  rows = 3,
  maxLength,
  error,
}) {
  return (
    <textarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      disabled={disabled}
      rows={rows}
      maxLength={maxLength}
      className={cn(
        "flex w-full rounded-xl border border-sand-dark bg-white px-4 py-3 text-sm text-charcoal placeholder:text-charcoal-subtle",
        "focus:outline-none focus:border-sage focus:ring-2 focus:ring-sage/20 resize-none",
        "disabled:opacity-50 disabled:bg-warm-gray",
        error && "border-red-400",
      )}
    />
  );
}

/* ---------- main form ---------- */

export default function PublicationForm({
  initialData,
  onSubmit,
  submitting,
  submitLabel,
}) {
  const { t } = useLanguage();
  const [form, setForm] = useState({ ...EMPTY, ...initialData });
  const [errors, setErrors] = useState({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(
    !initialData?.slug,
  );

  // Load experiences for the optional link
  const { data: experiences } = useExperiences({
    status: "published",
    limit: 100,
    offset: 0,
  });

  function set(field, value) {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (errors[field])
      setErrors((prev) => {
        const e = { ...prev };
        delete e[field];
        return e;
      });
  }

  function handleTitle(value) {
    set("title", value);
    if (slugAutoGenerated) {
      set("slug", slugify(value));
    }
  }

  function handleSlugChange(value) {
    setSlugAutoGenerated(false);
    set("slug", value);
  }

  async function validate() {
    const e = {};
    if (!form.title.trim()) e.title = t("admin.publicationForm.titleRequired");
    if (!form.slug.trim()) {
      e.slug = t("admin.publicationForm.slugRequired");
    } else if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(form.slug)) {
      e.slug = t("admin.publicationForm.slugInvalid");
    } else {
      const available = await checkSlugAvailable(form.slug, initialData?.$id);
      if (!available) e.slug = t("admin.publicationForm.slugTaken");
    }
    if (!form.category)
      e.category = t("admin.publicationForm.categoryRequired");
    return e;
  }

  async function handleSubmit(e) {
    e.preventDefault();
    const validationErrors = await validate();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    const payload = {
      title: form.title.trim(),
      titleEs: form.titleEs.trim() || null,
      slug: form.slug.trim(),
      subtitle: form.subtitle.trim() || null,
      subtitleEs: form.subtitleEs.trim() || null,
      excerpt: form.excerpt.trim() || null,
      excerptEs: form.excerptEs.trim() || null,
      category: form.category,
      experienceId: form.experienceId || null,
      heroImageId: form.heroImageId || null,
      status: form.status,
      publishedAt:
        form.status === "published" && !form.publishedAt
          ? new Date().toISOString()
          : form.publishedAt || null,
      seoTitle: form.seoTitle.trim() || null,
      seoDescription: form.seoDescription.trim() || null,
      ogImageId: form.ogImageId || null,
    };

    await onSubmit(payload);
  }

  const isDisabled = submitting;

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Identidad */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          {t("admin.publicationForm.sectionIdentity")}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field
            label={t("admin.publicationForm.titleEn")}
            required
            error={errors.title}
          >
            <Input
              value={form.title}
              onChange={(e) => handleTitle(e.target.value)}
              placeholder={t("admin.publicationForm.placeholderTitleEn")}
              disabled={isDisabled}
              className={errors.title ? "border-red-400" : ""}
            />
          </Field>
          <Field label={t("admin.publicationForm.titleEs")}>
            <Input
              value={form.titleEs}
              onChange={(e) => set("titleEs", e.target.value)}
              placeholder={t("admin.publicationForm.placeholderTitleEs")}
              disabled={isDisabled}
            />
          </Field>
          <Field
            label={t("admin.publicationForm.slug")}
            required
            error={errors.slug}
          >
            <SlugInput
              value={form.slug}
              onChange={handleSlugChange}
              error={errors.slug}
              disabled={isDisabled}
            />
          </Field>
          <Field
            label={t("admin.publicationForm.category")}
            required
            error={errors.category}
          >
            <AdminSelect
              value={form.category}
              onChange={(v) => set("category", v)}
              options={CATEGORY_OPTIONS.map((o) => ({
                ...o,
                label: t(o.i18nKey),
              }))}
              disabled={isDisabled}
              error={!!errors.category}
            />
          </Field>
        </div>
      </Card>

      {/* Subtítulos y extracto */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          {t("admin.publicationForm.sectionSubtitleExcerpt")}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field
            label={t("admin.publicationForm.subtitleEn")}
            hint={t("admin.publicationForm.maxChars500")}
          >
            <Input
              value={form.subtitle}
              onChange={(e) => set("subtitle", e.target.value)}
              placeholder={t("admin.publicationForm.placeholderSubtitleEn")}
              disabled={isDisabled}
              maxLength={500}
            />
          </Field>
          <Field label={t("admin.publicationForm.subtitleEs")}>
            <Input
              value={form.subtitleEs}
              onChange={(e) => set("subtitleEs", e.target.value)}
              placeholder={t("admin.publicationForm.placeholderSubtitleEs")}
              disabled={isDisabled}
              maxLength={500}
            />
          </Field>
          <Field
            label={t("admin.publicationForm.excerptEn")}
            hint={t("admin.publicationForm.excerptHint")}
          >
            <Textarea
              value={form.excerpt}
              onChange={(v) => set("excerpt", v)}
              placeholder={t("admin.publicationForm.placeholderExcerptEn")}
              disabled={isDisabled}
              rows={3}
            />
          </Field>
          <Field label={t("admin.publicationForm.excerptEs")}>
            <Textarea
              value={form.excerptEs}
              onChange={(v) => set("excerptEs", v)}
              placeholder={t("admin.publicationForm.placeholderExcerptEs")}
              disabled={isDisabled}
              rows={3}
            />
          </Field>
        </div>
      </Card>

      {/* Experiencia vinculada */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          {t("admin.publicationForm.sectionLinkedExperience")}
        </h2>
        <Field
          label={t("admin.publicationForm.experience")}
          hint={t("admin.publicationForm.experienceHint")}
        >
          <SearchCombobox
            value={form.experienceId}
            onValueChange={(v) => set("experienceId", v)}
            options={(experiences || []).map((exp) => ({
              value: exp.$id,
              label: exp.publicName || exp.name,
            }))}
            disabled={isDisabled}
            placeholder={t("admin.publicationForm.noExperience")}
            searchPlaceholder={t("admin.publicationForm.searchExperience")}
            emptyMessage={t("admin.publicationForm.noExperiences")}
          />
        </Field>
      </Card>

      {/* Imagen de portada */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          {t("admin.publicationForm.sectionCoverImage")}
        </h2>
        <div className="max-w-lg">
          <ImageUpload
            fileId={form.heroImageId}
            onUpload={(id) => set("heroImageId", id)}
            onRemove={() => set("heroImageId", "")}
            disabled={isDisabled}
          />
        </div>
      </Card>

      {/* Publicación */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          {t("admin.publicationForm.sectionPublication")}
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Field label={t("admin.publicationForm.status")} required>
            <AdminSelect
              value={form.status}
              onChange={(v) => set("status", v)}
              options={STATUS_OPTIONS.map((o) => ({
                ...o,
                label: t(o.i18nKey),
              }))}
              disabled={isDisabled}
            />
          </Field>
          {form.status === "published" && (
            <Field
              label={t("admin.publicationForm.publishDate")}
              hint={t("admin.publicationForm.publishDateHint")}
            >
              <Input
                type="datetime-local"
                value={form.publishedAt ? form.publishedAt.slice(0, 16) : ""}
                onChange={(e) =>
                  set(
                    "publishedAt",
                    e.target.value
                      ? new Date(e.target.value).toISOString()
                      : "",
                  )
                }
                disabled={isDisabled}
              />
            </Field>
          )}
        </div>
      </Card>

      {/* SEO */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          {t("admin.publicationForm.sectionSEO")}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field
            label={t("admin.publicationForm.seoTitle")}
            hint={t("admin.publicationForm.maxChars255")}
          >
            <Input
              value={form.seoTitle}
              onChange={(e) => set("seoTitle", e.target.value)}
              placeholder={t("admin.publicationForm.placeholderSeoTitle")}
              disabled={isDisabled}
              maxLength={255}
            />
          </Field>
          <Field
            label={t("admin.publicationForm.seoDescription")}
            hint={t("admin.publicationForm.maxChars500")}
          >
            <Textarea
              value={form.seoDescription}
              onChange={(v) => set("seoDescription", v)}
              placeholder={t("admin.publicationForm.placeholderSeoDescription")}
              disabled={isDisabled}
              maxLength={500}
              rows={2}
            />
          </Field>
        </div>
        <div className="max-w-lg">
          <Field
            label={t("admin.publicationForm.ogImage")}
            hint={t("admin.publicationForm.ogImageHint")}
          >
            <ImageUpload
              fileId={form.ogImageId}
              onUpload={(id) => set("ogImageId", id)}
              onRemove={() => set("ogImageId", "")}
              disabled={isDisabled}
            />
          </Field>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex items-center gap-3 pb-6">
        <Button type="submit" disabled={isDisabled} size="md">
          {submitting ? (
            <span className="flex items-center gap-2">
              <span className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin" />
              {t("admin.common.saving")}
            </span>
          ) : (
            submitLabel || t("admin.common.save")
          )}
        </Button>
      </div>
    </form>
  );
}
