export const ROUTES = {
  // Public
  HOME: "/",
  EXPERIENCES: "/experiences",
  EXPERIENCE: "/experiences/:slug",
  PACKAGES: "/packages",
  PACKAGE: "/packages/:slug",
  PASSES: "/passes",
  PASS: "/passes/:slug",
  ABOUT: "/about",
  CONTACT: "/contact",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  PUBLICATIONS: "/publications",
  PUBLICATION: "/p/:slug",

  // Auth
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_EMAIL_PENDING: "/verify-email-pending",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  FORBIDDEN: "/forbidden",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  CHECKOUT_CANCEL: "/checkout/cancel",

  // Customer portal
  PORTAL: "/portal",
  PORTAL_ORDERS: "/portal/orders",
  PORTAL_ORDER: "/portal/orders/:id",
  PORTAL_TICKETS: "/portal/tickets",
  PORTAL_TICKET_DETAIL: "/portal/tickets/:ticketId",
  PORTAL_PASSES: "/portal/passes",
  PORTAL_PROFILE: "/portal/profile",

  // Admin
  ADMIN: "/admin",
  ADMIN_EXPERIENCES: "/admin/experiences",
  ADMIN_EXPERIENCE_NEW: "/admin/experiences/new",
  ADMIN_EXPERIENCE_EDIT: "/admin/experiences/:id/edit",
  ADMIN_EXPERIENCE_EDITIONS: "/admin/experiences/:id/editions",
  ADMIN_EXPERIENCE_EDITION_NEW: "/admin/experiences/:id/editions/new",
  ADMIN_EXPERIENCE_EDITION_EDIT:
    "/admin/experiences/:id/editions/:editionId/edit",
  ADMIN_EXPERIENCE_PRICING: "/admin/experiences/:id/pricing",
  ADMIN_ADDONS: "/admin/addons",
  ADMIN_ADDON_NEW: "/admin/addons/new",
  ADMIN_ADDON_EDIT: "/admin/addons/:addonId/edit",
  ADMIN_EXPERIENCE_ADDONS: "/admin/experiences/:id/addons",
  ADMIN_EXPERIENCE_SLOTS: "/admin/experiences/:id/slots",
  ADMIN_EXPERIENCE_SLOT_CREATE: "/admin/experiences/:id/slots/create",
  ADMIN_EXPERIENCE_SLOT_QUICK_CREATE:
    "/admin/experiences/:id/slots/quick-create",
  ADMIN_EXPERIENCE_SLOT_EDIT: "/admin/experiences/:id/slots/:slotId/edit",
  ADMIN_PACKAGES: "/admin/packages",
  ADMIN_PACKAGE_NEW: "/admin/packages/new",
  ADMIN_PACKAGE_EDIT: "/admin/packages/:packageId/edit",
  ADMIN_PASSES: "/admin/passes",
  ADMIN_PASS_NEW: "/admin/passes/new",
  ADMIN_PASS_EDIT: "/admin/passes/:passId/edit",
  ADMIN_USER_PASSES: "/admin/user-passes",
  ADMIN_USER_PASS_DETAIL: "/admin/user-passes/:userPassId",
  ADMIN_SLOTS: "/admin/slots",
  ADMIN_RESOURCES: "/admin/resources",
  ADMIN_RESOURCE_NEW: "/admin/resources/new",
  ADMIN_RESOURCE_EDIT: "/admin/resources/:id/edit",
  ADMIN_LOCATION_NEW: "/admin/locations/new",
  ADMIN_LOCATION_EDIT: "/admin/locations/:id/edit",
  ADMIN_ROOM_NEW: "/admin/rooms/new",
  ADMIN_ROOM_EDIT: "/admin/rooms/:id/edit",
  ADMIN_SALES_NEW: "/admin/sales/new",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_ORDER_DETAIL: "/admin/orders/:orderId",
  ADMIN_TICKETS: "/admin/tickets",
  ADMIN_TICKET_DETAIL: "/admin/tickets/:ticketId",
  ADMIN_CHECK_IN: "/admin/check-in",
  ADMIN_CLIENTS: "/admin/clients",
  ADMIN_CLIENT_DETAIL: "/admin/clients/:userId",
  ADMIN_BOOKING_REQUESTS: "/admin/booking-requests",
  ADMIN_BOOKING_REQUEST_DETAIL: "/admin/booking-requests/:id",
  ADMIN_PUBLICATIONS: "/admin/publications",
  ADMIN_PUBLICATION_NEW: "/admin/publications/new",
  ADMIN_PUBLICATION_EDIT: "/admin/publications/:id/edit",
  ADMIN_PUBLICATION_SECTIONS: "/admin/publications/:id/sections",
  ADMIN_MEDIA: "/admin/media",
  ADMIN_ACCOUNT: "/admin/account",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_USERS: "/admin/users",
};
