import { useState, useEffect } from "react";
import { Input } from "@/components/common/Input";
import { Button } from "@/components/common/Button";
import { Card } from "@/components/common/Card";
import SlugInput from "./SlugInput";
import ImageUpload from "./ImageUpload";
import GalleryManager from "@/components/admin/media/GalleryManager";
import { slugify, checkSlugAvailable } from "@/hooks/useExperiences";
import AdminSelect from "@/components/common/AdminSelect";
import { cn } from "@/lib/utils";

const TYPE_OPTIONS = [
  { value: "session", label: "Sesión" },
  { value: "immersion", label: "Inmersión" },
  { value: "retreat", label: "Retiro" },
  { value: "stay", label: "Estancia" },
  { value: "private", label: "Privada" },
  { value: "package", label: "Paquete" },
];
const SALE_MODE_OPTIONS = [
  { value: "direct", label: "Directa" },
  { value: "request", label: "Por solicitud" },
  { value: "assisted", label: "Asistida" },
  { value: "pass", label: "Por pase" },
];
const FULFILLMENT_OPTIONS = [
  { value: "ticket", label: "Ticket" },
  { value: "booking", label: "Reserva" },
  { value: "pass", label: "Pase" },
  { value: "package", label: "Paquete" },
];
const STATUS_OPTIONS = [
  { value: "draft", label: "Borrador" },
  { value: "published", label: "Publicada" },
  { value: "archived", label: "Archivada" },
];

const EMPTY = {
  name: "",
  publicName: "",
  publicNameEs: "",
  slug: "",
  type: "session",
  saleMode: "direct",
  fulfillmentType: "ticket",
  shortDescription: "",
  shortDescriptionEs: "",
  longDescription: "",
  longDescriptionEs: "",
  heroImageId: "",
  galleryImageIds: [],
  requiresSchedule: false,
  requiresDate: false,
  allowQuantity: false,
  maxQuantity: "",
  minQuantity: "",
  generatesTickets: true,
  status: "draft",
  sortOrder: "",
  seoTitle: "",
  seoDescription: "",
};

function Field({ label, required, error, hint, children }) {
  return (
    <div className="space-y-1.5">
      <label className="text-sm font-medium text-charcoal">
        {label}
        {required && <span className="text-red-500 ml-0.5">*</span>}
      </label>
      {children}
      {error && <p className="text-xs text-red-600">{error}</p>}
      {hint && !error && <p className="text-xs text-charcoal-subtle">{hint}</p>}
    </div>
  );
}

function Toggle({ checked, onChange, label, disabled }) {
  return (
    <label className="flex items-center gap-3 cursor-pointer select-none">
      <button
        type="button"
        role="switch"
        aria-checked={checked}
        onClick={() => onChange(!checked)}
        disabled={disabled}
        className={cn(
          "relative w-10 h-6 rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-sage/40",
          checked ? "bg-sage" : "bg-sand-dark",
          "disabled:opacity-50 disabled:cursor-not-allowed",
        )}
      >
        <span
          className={cn(
            "absolute top-1 w-4 h-4 bg-white rounded-full shadow transition-transform",
            checked ? "translate-x-5" : "translate-x-1",
          )}
        />
      </button>
      <span className="text-sm text-charcoal">{label}</span>
    </label>
  );
}

function Textarea({
  value,
  onChange,
  placeholder,
  disabled,
  rows = 3,
  maxLength,
  error,
}) {
  return (
    <textarea
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      disabled={disabled}
      rows={rows}
      maxLength={maxLength}
      className={cn(
        "flex w-full rounded-xl border border-sand-dark bg-white px-4 py-3 text-sm text-charcoal placeholder:text-charcoal-subtle",
        "focus:outline-none focus:border-sage focus:ring-2 focus:ring-sage/20 resize-none",
        "disabled:opacity-50 disabled:bg-warm-gray",
        error && "border-red-400",
      )}
    />
  );
}

function parseJsonArray(val) {
  if (Array.isArray(val)) return val;
  if (!val) return [];
  try {
    return JSON.parse(val) ?? [];
  } catch {
    return [];
  }
}

export default function ExperienceForm({
  initialData,
  onSubmit,
  submitting,
  submitLabel = "Guardar",
}) {
  const [form, setForm] = useState(() => ({
    ...EMPTY,
    ...initialData,
    galleryImageIds: parseJsonArray(initialData?.galleryImageIds),
  }));
  const [errors, setErrors] = useState({});
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(
    !initialData?.slug,
  );

  function set(field, value) {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (errors[field])
      setErrors((prev) => {
        const e = { ...prev };
        delete e[field];
        return e;
      });
  }

  // Auto-generate slug from publicName
  function handlePublicName(value) {
    set("publicName", value);
    if (slugAutoGenerated) {
      set("slug", slugify(value));
    }
  }

  function handleSlugChange(value) {
    setSlugAutoGenerated(false);
    set("slug", value);
  }

  async function validate() {
    const e = {};
    if (!form.name.trim()) e.name = "El nombre interno es requerido";
    if (!form.publicName.trim())
      e.publicName = "El nombre público es requerido";
    if (!form.slug.trim()) {
      e.slug = "El slug es requerido";
    } else if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(form.slug)) {
      e.slug = "El slug solo puede contener minúsculas, números y guiones";
    } else {
      const available = await checkSlugAvailable(form.slug, initialData?.$id);
      if (!available) e.slug = "Este slug ya está en uso";
    }
    if (!form.type) e.type = "El tipo es requerido";
    if (!form.saleMode) e.saleMode = "El modo de venta es requerido";
    if (!form.fulfillmentType)
      e.fulfillmentType = "El fulfillment es requerido";
    return e;
  }

  async function handleSubmit(e) {
    e.preventDefault();
    const validationErrors = await validate();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    const payload = {
      name: form.name.trim(),
      publicName: form.publicName.trim(),
      publicNameEs: form.publicNameEs.trim() || null,
      slug: form.slug.trim(),
      type: form.type,
      saleMode: form.saleMode,
      fulfillmentType: form.fulfillmentType,
      shortDescription: form.shortDescription.trim() || null,
      shortDescriptionEs: form.shortDescriptionEs.trim() || null,
      longDescription: form.longDescription.trim() || null,
      longDescriptionEs: form.longDescriptionEs.trim() || null,
      heroImageId: form.heroImageId || null,
      galleryImageIds:
        form.galleryImageIds.length > 0
          ? JSON.stringify(form.galleryImageIds)
          : null,
      requiresSchedule: form.requiresSchedule,
      requiresDate: form.requiresDate,
      allowQuantity: form.allowQuantity,
      maxQuantity:
        form.allowQuantity && form.maxQuantity
          ? parseInt(form.maxQuantity)
          : null,
      minQuantity:
        form.allowQuantity && form.minQuantity
          ? parseInt(form.minQuantity)
          : null,
      generatesTickets: form.generatesTickets,
      status: form.status,
      sortOrder: form.sortOrder ? parseInt(form.sortOrder) : null,
      seoTitle: form.seoTitle.trim() || null,
      seoDescription: form.seoDescription.trim() || null,
    };

    await onSubmit(payload);
  }

  const isDisabled = submitting;

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Identidad */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Identidad
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field label="Nombre interno" required error={errors.name}>
            <Input
              value={form.name}
              onChange={(e) => set("name", e.target.value)}
              placeholder="Yoga Sunrise — nombre operativo"
              disabled={isDisabled}
              className={errors.name ? "border-red-400" : ""}
            />
          </Field>
          <Field label="Nombre público (EN)" required error={errors.publicName}>
            <Input
              value={form.publicName}
              onChange={(e) => handlePublicName(e.target.value)}
              placeholder="Sunrise Yoga Experience"
              disabled={isDisabled}
              className={errors.publicName ? "border-red-400" : ""}
            />
          </Field>
          <Field label="Nombre público (ES)">
            <Input
              value={form.publicNameEs}
              onChange={(e) => set("publicNameEs", e.target.value)}
              placeholder="Experiencia de Yoga al Amanecer"
              disabled={isDisabled}
            />
          </Field>
          <Field label="Slug (URL)" required error={errors.slug}>
            <SlugInput
              value={form.slug}
              onChange={handleSlugChange}
              error={errors.slug}
              disabled={isDisabled}
            />
          </Field>
        </div>
      </Card>

      {/* Clasificación */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Clasificación
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <Field label="Tipo" required error={errors.type}>
            <AdminSelect
              value={form.type}
              onChange={(v) => set("type", v)}
              options={TYPE_OPTIONS}
              disabled={isDisabled}
              error={errors.type}
            />
          </Field>
          <Field label="Modo de venta" required error={errors.saleMode}>
            <AdminSelect
              value={form.saleMode}
              onChange={(v) => set("saleMode", v)}
              options={SALE_MODE_OPTIONS}
              disabled={isDisabled}
              error={errors.saleMode}
            />
          </Field>
          <Field label="Fulfillment" required error={errors.fulfillmentType}>
            <AdminSelect
              value={form.fulfillmentType}
              onChange={(v) => set("fulfillmentType", v)}
              options={FULFILLMENT_OPTIONS}
              disabled={isDisabled}
              error={errors.fulfillmentType}
            />
          </Field>
        </div>
      </Card>

      {/* Descripción */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Descripción
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field label="Descripción corta (EN)" hint="Máx. 500 caracteres">
            <Textarea
              value={form.shortDescription}
              onChange={(v) => set("shortDescription", v)}
              placeholder="A transformative sunrise yoga session..."
              disabled={isDisabled}
              maxLength={500}
            />
          </Field>
          <Field label="Descripción corta (ES)">
            <Textarea
              value={form.shortDescriptionEs}
              onChange={(v) => set("shortDescriptionEs", v)}
              placeholder="Una sesión de yoga transformadora al amanecer..."
              disabled={isDisabled}
              maxLength={500}
            />
          </Field>
          <Field label="Descripción larga (EN)" hint="Máx. 5000 caracteres">
            <Textarea
              value={form.longDescription}
              onChange={(v) => set("longDescription", v)}
              placeholder="Full description in English..."
              disabled={isDisabled}
              rows={5}
              maxLength={5000}
            />
          </Field>
          <Field label="Descripción larga (ES)">
            <Textarea
              value={form.longDescriptionEs}
              onChange={(v) => set("longDescriptionEs", v)}
              placeholder="Descripción completa en español..."
              disabled={isDisabled}
              rows={5}
              maxLength={5000}
            />
          </Field>
        </div>
      </Card>

      {/* Imagen de portada */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Imagen de portada
        </h2>
        <div className="max-w-lg">
          <ImageUpload
            fileId={form.heroImageId}
            onUpload={(id) => set("heroImageId", id)}
            onRemove={() => set("heroImageId", "")}
            disabled={isDisabled}
          />
        </div>
      </Card>

      {/* Galería de imágenes */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Galería
        </h2>
        <GalleryManager
          value={form.galleryImageIds}
          onChange={(ids) => set("galleryImageIds", ids)}
          isAdmin
          disabled={isDisabled}
        />
      </Card>

      {/* Comportamiento */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Comportamiento
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Toggle
            checked={form.requiresSchedule}
            onChange={(v) => set("requiresSchedule", v)}
            label="Requiere selección de fecha/slot"
            disabled={isDisabled}
          />
          <Toggle
            checked={form.requiresDate}
            onChange={(v) => set("requiresDate", v)}
            label="Requiere fecha específica"
            disabled={isDisabled}
          />
          <Toggle
            checked={form.generatesTickets}
            onChange={(v) => set("generatesTickets", v)}
            label="Genera tickets tras compra"
            disabled={isDisabled}
          />
          <Toggle
            checked={form.allowQuantity}
            onChange={(v) => set("allowQuantity", v)}
            label="Permite múltiples asistentes"
            disabled={isDisabled}
          />
        </div>
        {form.allowQuantity && (
          <div className="grid grid-cols-2 gap-4 pt-2">
            <Field label="Mínimo de asistentes">
              <Input
                type="number"
                min={1}
                value={form.minQuantity}
                onChange={(e) => set("minQuantity", e.target.value)}
                placeholder="1"
                disabled={isDisabled}
              />
            </Field>
            <Field label="Máximo de asistentes">
              <Input
                type="number"
                min={1}
                value={form.maxQuantity}
                onChange={(e) => set("maxQuantity", e.target.value)}
                placeholder="10"
                disabled={isDisabled}
              />
            </Field>
          </div>
        )}
      </Card>

      {/* Publicación */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          Publicación
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Field label="Estado" required>
            <AdminSelect
              value={form.status}
              onChange={(v) => set("status", v)}
              options={STATUS_OPTIONS}
              disabled={isDisabled}
            />
          </Field>
          <Field
            label="Orden de visualización"
            hint="Número para ordenar en listado público"
          >
            <Input
              type="number"
              min={0}
              value={form.sortOrder}
              onChange={(e) => set("sortOrder", e.target.value)}
              placeholder="0"
              disabled={isDisabled}
            />
          </Field>
        </div>
      </Card>

      {/* SEO */}
      <Card className="p-5 space-y-4">
        <h2 className="text-sm font-semibold text-charcoal-subtle uppercase tracking-wider">
          SEO
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Field label="SEO Title" hint="Máx. 255 caracteres">
            <Input
              value={form.seoTitle}
              onChange={(e) => set("seoTitle", e.target.value)}
              placeholder="Sunrise Yoga Experience | OMZONE"
              disabled={isDisabled}
              maxLength={255}
            />
          </Field>
          <Field label="SEO Description" hint="Máx. 500 caracteres">
            <Textarea
              value={form.seoDescription}
              onChange={(v) => set("seoDescription", v)}
              placeholder="Discover our transformative sunrise yoga..."
              disabled={isDisabled}
              maxLength={500}
              rows={2}
            />
          </Field>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex items-center gap-3 pb-6">
        <Button type="submit" disabled={isDisabled} size="md">
          {submitting ? (
            <span className="flex items-center gap-2">
              <span className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin" />
              Guardando...
            </span>
          ) : (
            submitLabel
          )}
        </Button>
      </div>
    </form>
  );
}
